services:
  test:
    image: pbatey/jupyter-datascience-notebook-gpu:2021apr07
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]